name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: "Login to GitHub Registry"
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: "rednakse"
        password: ${{ secrets.PACKAGES }}

    - name: "Build&Deploy template-server"
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/gusd:latest
